### ISSUE TITLE
No streaming links

### ISSUE THREAD

**Issue by enusri** [ston3o/netclix#11]
i installed just as descridbed here. 1. node.js, 2. npm command and 3. netclix and type in the movie, its searching the movies and if it has more than one part, it lets me select the movie i want, but all the three movies i tried there is no streaming link.  any suggestion?

thanks in advance.

**Comment by johackim** [comment]
Hello @enusri,

Now the bug is fixed, you can upgrade netclix `npm install -g netclix`

;)

**Comment by 1337miro** [comment]
Having the same issue, no matter what movie I look for netclix gives me this error:
`Failed to GET url:`
