### ISSUE TITLE
Unable to install on Ubuntu 20.04 CLI

### ISSUE THREAD

**Issue by jakubroj** [ston3o/netclix#24]
Hello, I'm unable to install Netclix on my Ubuntu 20.04 machine. I'm connected to it via ssh as it is a free compute instance with Oracle Cloud.

This is what I can see:
![image](https://user-images.githubusercontent.com/17677358/112739874-d99cb600-8f6f-11eb-9b6b-4bf942f383ee.png)

Log is attached here:
[2021-03-28T01_38_56_662Z-debug.log](https://github.com/johackim/netclix/files/6216714/2021-03-28T01_38_56_662Z-debug.log)

Any help would be much appreciated. 

Thanks, 
Jakub

**Comment by johackim** [comment]
Hello @jakubroj, sorry, the service benhind netclix is closed, so the tool doesn't work anymore :(
