### ISSUE TITLE
Its not free software, its open software

### ISSUE THREAD

**Issue by madnight** [ston3o/netclix#9]
"Free Software, Hell Yeah" thats not quiet correct, since MIT is a open source software license, not a free software license in the sense that it protects the users rights, thats a difference. However it is a free software compatible license and you can upgrade to a free user protective license. Maybe you noticed the movement of openoffice to libreoffice and openelec to libreelec and many more ...

That is the best  explanation i know of https://youtu.be/Ag1AKIl_2GM

**Comment by Arudarin** [comment]
Ah, sorry, that was present in the fork, and I didn't catch that!

Edit: This isn't my fork. Crap.

**Comment by johackim** [comment]
You are right @madnight, I changed it my README ;)
